### ISSUE TITLE
Add API to upload a real state information.

### ISSUE THREAD

**Issue by argjv** [argjv/api-realtor#1]
-[ ] The user can store a real estate address, sq feet, rooms description, pictures and built year

**Comment by suprematis** [comment]
Acknowledging assigment.

**Comment by suprematis** [comment]
So far so good, only two properties show on my database. 
![image](https://user-images.githubusercontent.com/24498458/37454616-46b32cc0-27f8-11e8-9807-c0b403c84f1d.png)

I was able to successfully connect to my dockerized MongoDB local instance on port 27107 (follow the instructions on the README.  

I get a message with a successful connection to the database, so the MongoDB module is storing data correctly on the database.
![image](https://user-images.githubusercontent.com/24498458/37454855-e008c420-27f8-11e8-9ba1-6659e5ed0f14.png)

I was able to create a new successfully run GET and DELETE on the database.  I am getting an error when trying to create a new property:
`{ _id: 5aaa3a82602e03377e7a497e,
  owner: 'Andres',
  address1: '100 Test Address',
  address2: '',
  createdAt: 2018-03-15T09:18:58.807Z,
  updatedAt: 2018-03-15T09:18:58.807Z,
  __v: 0 }
{ _id: 5aaa3aeb602e03377e7a497f,
  address2: '',
  createdAt: 2018-03-15T09:20:43.254Z,
  updatedAt: 2018-03-15T09:20:43.254Z,
  __v: 0 }
/home/suprematis/CSC690/api-realtor/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (/home/suprematis/CSC690/api-realtor/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/suprematis/CSC690/api-realtor/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/home/suprematis/CSC690/api-realtor/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/home/suprematis/CSC690/api-realtor/node_modules/express/lib/response.js:158:21)
    at /home/suprematis/CSC690/api-realtor/app/controllers/property.controller.js:20:17
    at /home/suprematis/CSC690/api-realtor/node_modules/mongoose/lib/model.js:3928:16
    at model.$__save.error (/home/suprematis/CSC690/api-realtor/node_modules/mongoose/lib/model.js:343:7)
    at /home/suprematis/CSC690/api-realtor/node_modules/kareem/index.js:297:21
    at next (/home/suprematis/CSC690/api-realtor/node_modules/kareem/index.js:209:27)
    at Kareem.execPost (/home/suprematis/CSC690/api-realtor/node_modules/kareem/index.js:217:3)
    at _cb (/home/suprematis/CSC690/api-realtor/node_modules/kareem/index.js:289:15)
    at $__handleSave (/home/suprematis/CSC690/api-realtor/node_modules/mongoose/lib/model.js:281:5)
    at /home/suprematis/CSC690/api-realtor/node_modules/mongoose/lib/model.js:168:7
    at session.endSession (/home/suprematis/CSC690/api-realtor/node_modules/mongodb/lib/utils.js:400:34)
    at ClientSession.endSession (/home/suprematis/CSC690/api-realtor/node_modules/mongodb-core/lib/sessions.js:69:41)
suprematis@sirisaac:~/CSC690/api-realtor$ node server.js`

I suspect it has something to do with the Middleware layer.
